config/routes.rb
Rails.application.routes.draw do
  resources :tasklists do
    resources :tasks
  end

  root 'home#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :tasklist
  validates :title, presence: true
  validates :description, presence: true

  scope :actual, -> { where created_at: Date.today - 1.month }
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'tasklists'

  def show

  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :set_tasklist, only: %i[show edit update destroy]

  layout 'tasklists'

  # GET /tasklists
  # GET /tasklists.json
  def index
    @tasklists = Tasklist.all
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show; end

  # GET /tasklists/new
  def new
    @tasklist = Tasklist.new
  end

  # GET /tasklists/1/edit
  def edit; end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(tasklist_params)

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render :show, status: :created, location: @tasklist }
      else
        format.html { render :new }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasklists/1
  # PATCH/PUT /tasklists/1.json
  def update
    respond_to do |format|
      if @tasklist.update(tasklist_params)
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasklist }
      else
        format.html { render :edit }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist.destroy
    respond_to do |format|
      format.html { redirect_to tasklists_url, notice: 'Tasklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tasklist
    @tasklist = Tasklist.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tasklist_params
    params.require(:tasklist).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_tasklist
  before_action :set_task, only: %i[show edit update destroy]


  layout 'tasks'
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @tasklist.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = @tasklist.tasks.build
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @tasklist.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasklist_tasks_path(@tasklist), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasklist_tasks_path(@tasklist), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasklist_tasks_path(@tasklist), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_tasklist
    @tasklist = Tasklist.find(params[:tasklist_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = @tasklist.tasks.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :description, :tasklist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_header.html.slim
header.header
  .logo Trello
  nav.header__menu
    = link_to 'Home', root_path, class: 'header__link'
    = link_to 'Tasklists', tasklists_path, class: 'header__link header__link--main'

app/views/home/show.html.slim
doctype html
html
  head
    title Trello
    / meta name="keywords" content="template language"
    / meta name="author" content=author
    / link rel="icon" type="image/png" href=file_path("favicon.png")

  body

    h1 Welcome to Trello

    .content
      p Welcome

    .footer
      = render 'footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Trello
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = yield

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/tasklists.html.slim
doctype html
html
  head
    title
      | Trello
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = render 'header'
    main.content
      = yield

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/tasks.html.slim
doctype html
html
  head
    title
      | Trello
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = render 'header'
    main.content
      = yield
    = render 'footer'

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/tasklists/_form.html.slim
= form_with(model: tasklist, local: true) do |form|
  - if tasklist.errors.any?
    #error_explanation
      h2
        = pluralize(tasklist.errors.count, 'error')
        |  prohibited this tasklist from being saved:
      ul
        - tasklist.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .actions
    = form.submit

app/views/tasklists/edit.html.slim
h1
  | Editing Tasklist
= render 'form', tasklist: @tasklist
= link_to 'Show', @tasklist
|  | 
= link_to 'Back', tasklists_path

app/views/tasklists/index.html.slim
.js-tasklists
  .message.message--notice = notice

  h1
    ' Tasklists
    span.sorter.js-sort-asc Sort by title ascendant
    span.sorter.js-sort-desc.hidden Sort by title descendant

  ul.tasklists-list.js-tasklists-list
    - @tasklists.each do |tasklist|
      li.tasklists-list__item.js-item data-tasklist=tasklist.to_json
        .tasklists-list__header
          = link_to tasklist.title, tasklist
        .tasklists-list__comments
        .tasklists-list__icons
          = link_to edit_tasklist_path(tasklist), class: 'tasklists-list__icon' do
            = image_tag 'edit.svg'
          = link_to tasklist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tasklists-list__icon' do
            = image_tag 'destroy.svg'

  = link_to 'New Tasklist', new_tasklist_path, class: 'button'

app/views/tasklists/new.html.slim
h1
  | New Tasklist
= render 'form', tasklist: @tasklist
= link_to 'Back', tasklists_path

app/views/tasklists/show.html.slim
.message.message--notice = notice
.message.message--alert = alert

h2
  | Tasklist
    | |
  = @tasklist.title
- for task in @tasklist.tasks
  ul.tasks-list
    li.tasks-list__item
      = task.description
= link_to 'Edit Tasklist', edit_tasklist_path(@tasklist)
| |
= link_to 'Manage Tasks', tasklist_tasks_path(@tasklist)
| |
= link_to 'Back', tasklists_path

app/views/tasks/_form.html.slim
= form_with(model: [@tasklist, task], local: true) do |form|
  - if task.errors.any?
    #error_explanation
      h2
        = pluralize(task.errors.count, "error")
        |  prohibited this task from being saved:
      ul
        - task.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_area :description
  .actions
    = form.submit

app/views/tasks/edit.html.slim
h1
  | Editing Task
= render 'form', task: @task
= link_to 'Show', [@tasklist, @task]
|  | 
= link_to 'Back', tasklist_tasks_path(@tasklist)

app/views/tasks/index.html.slim
.message.message--notice = notice

h1 Tasks

ul.tasks-list
  - @tasks.each do |task|
    li.tasks-list__item
      .tasks-list__header
        = link_to task.title, @task
      .tasks-list__description
        = task.description
      .tasks-list__tasklist
        = link_to task.tasklist.title, [@tasklist]
      .tasks-list__comments
      .tasks-list__icons
        = link_to edit_tasklist_task_path(@tasklist, task), class: 'tasks-list__icon' do
          = image_tag 'edit.svg'
        = link_to [@tasklist, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'tasks-list__icon' do
          = image_tag 'destroy.svg'

= link_to 'New Task', new_tasklist_task_path(@tasklist), class: 'button'

app/views/tasks/new.html.slim
h1
  | New Task
= render 'form', task: @task
= link_to 'Back', tasklist_tasks_path(@tasklist)

app/views/tasks/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @task.title
p
  strong
    | Description:
  = @task.description
p
  strong
    | Tasklist:
  = @task.tasklist_id
= link_to 'Edit', edit_tasklist_task_path(@tasklist, @task)
|  | 
= link_to 'Back', tasklist_tasks_path(@tasklist)